[package]
name = "zakuro-gpu"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
opengl = ["dep:glow"]
vulkan = ["dep:ash", "dep:ash-window"]

[dependencies]
zakuro-common.workspace = true
log.workspace = true
bitflags.workspace = true
thiserror.workspace = true
rayon.workspace = true
raw-window-handle = "0.6"

glow = { version = "0.16", optional = true }
ash = { version = "0.38", optional = true, default-features = false, features = ["loaded", "std"] }
ash-window = { version = "0.13", optional = true }
